Traceback (most recent call last):
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/conda/envs/ofs/lib/python3.13/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# BAR PLOT

width = 0.2
plt.figure(figsize=(10,5), dpi=300)
plt.bar(df.index-datetime.timedelta(hours=5), df['watertemp'], color='b', label='watertemp', align='edge', width=0.4)
plt.bar(df.index+datetime.timedelta(hours=5), df['temp'], color='r', label='airtemp', align='edge', width=0.4)
plt.xticks(rotation=40)
plt.xlabel("Time")
plt.ylabel("Temp (degC)")
plt.title("Plot Watertemp dan Airtemp di AWS TJ Priok")
plt.legend(loc='lower right', bbox_to_anchor=(1.2,0.05))
fig.tight_layout()
plt.show()
------------------


[31m---------------------------------------------------------------------------[39m
[31mNameError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 12[39m
[32m     10[39m plt.title([33m"[39m[33mPlot Watertemp dan Airtemp di AWS TJ Priok[39m[33m"[39m)
[32m     11[39m plt.legend(loc=[33m'[39m[33mlower right[39m[33m'[39m, bbox_to_anchor=([32m1.2[39m,[32m0.05[39m))
[32m---> [39m[32m12[39m [43mfig[49m.tight_layout()
[32m     13[39m plt.show()

[31mNameError[39m: name 'fig' is not defined

